### ISSUE TITLE
Clean up routes.

### ISSUE THREAD

**Issue by gigamorph** [ten-thousand-rooms/ten-thousand-rooms-annotation-server#44]
Routes in config/routes.rb contains duplicate routes in a confusing way. 
For example, there are "resources annotations", "resources annotation", "put annotation", and "delete annotation", "match annotation", and "match annotations" when one resources declaration for "annotations" should be enough.

The confusion seems to be partly caused by unconventional naming of the controller: annotations_controller. By rails convention it should named with a plural: annotations_controller.rb. Then "resources :annotations" should route everything correctly.

**Comment by rlechich** [comment]
re-named controllers for annotations, lists and layers.  Server now uses "resources:annotations" to supply routes for the basic CRUD methods
