### ISSUE TITLE
Creating annotation IDs

### ISSUE THREAD

**Issue by gigamorph** [ten-thousand-rooms/ten-thousand-rooms-annotation-server#45]
Currently the "@id" field seems to be created from "original_url", which is very brittle. The prefix will change the moment the server's public address changes, even when the protocol changes from "http://" to "https://". Wouldn't it be better to follow the model of Harvard "Catcha" and use only the UUID part as the internal ID or primary key, and let the Mirador endpoint convert to and from the full URI? 

In any case, the server should keep serving correct records for the URI request, e.g., http://{host}/annotations/{hash} , http://{host}/iiif/annotations/{hash} or whatever we agree on.

**Comment by gigamorph** [comment]
Please forget about what I said about Harvard Catcha. It was another end point and I got it all backwards – the annotation server sends "full" URI/ID, mirador internally uses the UUID sub-part of it. So as long as the annotation server is concerned, it doesn't matter. Sorry about the confusion. So our concern should only be on generating "consistent" and "web-accessible" URIs.

**Comment by rlechich** [comment]
But your point about brittleness is well-taken, so we should resolve the question of url aliases which we can use regardless of actual deployment.  
If we have http://yale.edu/ten_thousand_rooms/annotations set as an alias for example, then we could immediately set the heroku instance to be aware of it.
