### ISSUE TITLE
Multiple same annotation created?

### ISSUE THREAD

**Issue by gigamorph** [ten-thousand-rooms/ten-thousand-rooms-annotation-server#48]
After I have created an annotation, when I do read, more often than not I get multiple (2, 3, or 4) same annotations. It seems either multiple objects were created for a single request or "read" is returning multiple objects for a single entry.

For example: http://ten-thousand-rooms.herokuapp.com/getAnnotations?canvas_id=http%3A%2F%2Fmanifests.ydc2.yale.edu%2Fcanvas%2FRPNT001-001-tif

**Comment by rlechich** [comment]
This was a new bug in the code to handle adding the required layer/canvas list.  The "checkIfListExists" method was using the wrong variable.  Also required some data cleanup for the errant lists created.
